# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-02 06:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureADConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=64)),
                ('tenant_id', models.CharField(max_length=64)),
                ('client_id', models.CharField(max_length=64)),
                ('client_secret', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MicrosoftAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microsoft_id', models.CharField(max_length=64, verbose_name='microsoft account id')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='microsoft_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
