# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-10 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SQLMobileAuthKeyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=126)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('valid', models.DateTimeField()),
                ('expires', models.DateTimeField()),
                ('type', models.CharField(choices=[('AES256', 'AES256')], default='AES256', max_length=32)),
                ('key', models.CharField(max_length=127)),
                ('couch_id', models.CharField(db_index=True, max_length=126, null=True)),
            ],
            options={
                'db_table': 'mobile_auth_mobileauthkeyrecord',
            },
        ),
    ]
